"""Contract tests — verify daemon FastAPI routes match the OpenAPI specs in docs/.

Strategy:
  1. Load participant-api.yaml and host-api.yaml (the authoritative specs).
  2. Start the daemon host_server app via TestClient (no actual network calls).
  3. Fetch /openapi.json from the running app to get the actual routes.
  4. Compare: every path+method in each spec must exist in the app's OpenAPI.
  5. Also report extra routes on the app not documented in either spec.

The participant routes live under /api/participant/...
The host routes live under /api/{session_id}/host/... (plus /api/{session_id}/quiz-md)
"""
import re
from pathlib import Path

import pytest
import yaml
from starlette.testclient import TestClient

DOCS_DIR = Path(__file__).parent.parent.parent / "docs"
PARTICIPANT_SPEC_PATH = DOCS_DIR / "participant-api.yaml"
HOST_SPEC_PATH = DOCS_DIR / "host-api.yaml"

# Concrete session_id to use when expanding {session_id} placeholders in spec paths
_EXAMPLE_SESSION_ID = "abc123"

# Routes generated by FastAPI infrastructure that are not part of the API spec
_FASTAPI_INTERNAL_PREFIXES = {"/openapi.json", "/docs", "/redoc"}

# Routes that are intentionally in the daemon but not in either YAML spec
# (proxy catch-all, static files, WS, host HTML page, session/transcript endpoints)
_KNOWN_UNSPECCED_PREFIXES = (
    "/api/{path:path}",          # catch-all Railway proxy
    "/ws/",                      # WebSocket proxy
    "/host",                     # host HTML page
    "/static",                   # static files
    "/api/session/",             # session lifecycle (not yet in spec)
    "/api/{session_id}/session", # session-scoped endpoints (not yet in spec)
)


def _load_spec(path: Path) -> dict:
    return yaml.safe_load(path.read_text())


def _expand_session_id(path: str) -> str:
    """Replace {session_id} placeholder with a concrete value for comparison."""
    return path.replace("{session_id}", _EXAMPLE_SESSION_ID)


def _spec_paths_to_route_set(spec: dict) -> set[tuple[str, str]]:
    """Return set of (METHOD, path) from a YAML spec's paths section.

    Paths use the spec's own variable syntax (e.g., {question_id}).
    We don't expand {session_id} here — we use the app's concrete OpenAPI instead.
    """
    result = set()
    for path, methods in spec.get("paths", {}).items():
        for method, _operation in methods.items():
            if method.lower() in ("get", "post", "put", "delete", "patch"):
                result.add((method.upper(), path))
    return result


def _app_paths_to_route_set(openapi: dict) -> set[tuple[str, str]]:
    """Return set of (METHOD, path) from FastAPI's generated OpenAPI JSON."""
    result = set()
    for path, methods in openapi.get("paths", {}).items():
        for method in methods:
            if method.lower() in ("get", "post", "put", "delete", "patch"):
                result.add((method.upper(), path))
    return result


def _paths_match(spec_path: str, app_path: str) -> bool:
    """Check if a spec path matches an app path, treating {param} as wildcards.

    Example:
        spec:  /host/qa/question/{question_id}/text
        app:   /api/abc123/host/qa/question/{question_id}/text
    """
    # Normalise both paths: replace any {xxx} with a common placeholder
    def _normalise(p: str) -> str:
        return re.sub(r"\{[^}]+\}", "{P}", p)

    return _normalise(spec_path) == _normalise(app_path)


def _find_app_match(method: str, spec_path: str, app_routes: set[tuple[str, str]]) -> bool:
    """Return True if the app has a matching route for (method, spec_path)."""
    for app_method, app_path in app_routes:
        if app_method == method and _paths_match(spec_path, app_path):
            return True
    return False


@pytest.fixture(scope="module")
def app_openapi():
    """Build the daemon app and return its OpenAPI JSON (no real network calls)."""
    from daemon.host_server import create_app
    app = create_app("http://test-backend")
    # docs_url must be set for /openapi.json to be available
    app.openapi_url = "/openapi.json"
    client = TestClient(app, raise_server_exceptions=False)
    resp = client.get("/openapi.json")
    assert resp.status_code == 200, f"Failed to fetch /openapi.json: {resp.status_code}"
    return resp.json()


@pytest.fixture(scope="module")
def app_routes(app_openapi):
    """Set of (METHOD, path) actually registered on the daemon app."""
    return _app_paths_to_route_set(app_openapi)


# ── Test: participant spec completeness ────────────────────────────────────────

class TestParticipantApiContract:
    """All paths in participant-api.yaml must exist on the daemon with correct method."""

    def test_all_spec_endpoints_exist_in_app(self, app_routes):
        spec = _load_spec(PARTICIPANT_SPEC_PATH)
        spec_routes = _spec_paths_to_route_set(spec)

        # Participant spec paths use the base /api/participant prefix per the
        # server URL in the YAML.  App paths look like /api/participant/register.
        # The spec omits the /api/participant prefix (it's in the server URL),
        # so we reconstruct the full path.
        base_prefix = "/api/participant"

        missing = []
        for method, path in sorted(spec_routes):
            full_path = base_prefix + path
            if not _find_app_match(method, full_path, app_routes):
                missing.append(f"  {method} {full_path}  (spec: {path})")

        assert not missing, (
            f"Endpoints in participant-api.yaml missing from daemon app:\n"
            + "\n".join(missing)
        )

    def test_no_obviously_missing_participant_routes(self, app_routes):
        """Sanity: core participant endpoints are present."""
        required = [
            ("POST", "/api/participant/register"),
            ("PUT",  "/api/participant/name"),
            ("POST", "/api/participant/avatar"),
            ("POST", "/api/participant/location"),
            ("GET",  "/api/participant/state"),
            ("POST", "/api/participant/poll/vote"),
            ("POST", "/api/participant/wordcloud/word"),
            ("POST", "/api/participant/qa/submit"),
            ("POST", "/api/participant/qa/upvote"),
            ("PUT",  "/api/participant/codereview/selection"),
            ("POST", "/api/participant/debate/pick-side"),
            ("POST", "/api/participant/debate/argument"),
            ("POST", "/api/participant/debate/upvote"),
            ("POST", "/api/participant/debate/volunteer"),
            ("POST", "/api/participant/emoji/reaction"),
            ("POST", "/api/participant/misc/paste"),
            ("POST", "/api/participant/misc/feedback"),
            ("GET",  "/api/participant/misc/notes"),
            ("GET",  "/api/participant/misc/summary"),
            ("GET",  "/api/participant/misc/slides-cache-status"),
        ]
        missing = [
            f"{m} {p}" for m, p in required
            if not _find_app_match(m, p, app_routes)
        ]
        assert not missing, "Core participant routes missing:\n" + "\n".join(missing)


# ── Test: host spec completeness ───────────────────────────────────────────────

class TestHostApiContract:
    """All paths in host-api.yaml must exist on the daemon with correct method."""

    def test_all_spec_endpoints_exist_in_app(self, app_routes):
        spec = _load_spec(HOST_SPEC_PATH)
        spec_routes = _spec_paths_to_route_set(spec)

        # Host spec uses server base http://localhost:8081/api/{session_id}
        # App paths look like /api/{session_id}/host/state.
        # Spec paths are relative to that base, e.g. /host/state.
        base_prefix = "/api/{session_id}"

        missing = []
        for method, path in sorted(spec_routes):
            full_path = base_prefix + path
            if not _find_app_match(method, full_path, app_routes):
                missing.append(f"  {method} {full_path}  (spec: {path})")

        assert not missing, (
            f"Endpoints in host-api.yaml missing from daemon app:\n"
            + "\n".join(missing)
        )

    def test_no_obviously_missing_host_routes(self, app_routes):
        """Sanity: core host endpoints are present."""
        required = [
            ("GET",    "/api/{session_id}/host/state"),
            ("POST",   "/api/{session_id}/host/poll"),
            ("DELETE", "/api/{session_id}/host/poll"),
            ("POST",   "/api/{session_id}/host/poll/open"),
            ("POST",   "/api/{session_id}/host/poll/close"),
            ("PUT",    "/api/{session_id}/host/poll/correct"),
            ("POST",   "/api/{session_id}/host/poll/timer"),
            ("GET",    "/api/{session_id}/quiz-md"),
            ("POST",   "/api/{session_id}/host/wordcloud/word"),
            ("POST",   "/api/{session_id}/host/wordcloud/topic"),
            ("POST",   "/api/{session_id}/host/wordcloud/clear"),
            ("POST",   "/api/{session_id}/host/qa/submit"),
            ("DELETE", "/api/{session_id}/host/qa/question/{question_id}"),
            ("PUT",    "/api/{session_id}/host/qa/question/{question_id}/text"),
            ("PUT",    "/api/{session_id}/host/qa/question/{question_id}/answered"),
            ("POST",   "/api/{session_id}/host/qa/clear"),
            ("POST",   "/api/{session_id}/host/codereview"),
            ("DELETE", "/api/{session_id}/host/codereview"),
            ("PUT",    "/api/{session_id}/host/codereview/status"),
            ("PUT",    "/api/{session_id}/host/codereview/confirm-line"),
            ("POST",   "/api/{session_id}/host/debate"),
            ("POST",   "/api/{session_id}/host/debate/reset"),
            ("POST",   "/api/{session_id}/host/leaderboard/show"),
            ("POST",   "/api/{session_id}/host/leaderboard/hide"),
            ("DELETE", "/api/{session_id}/host/scores"),
            ("POST",   "/api/{session_id}/host/activity"),
            ("POST",   "/api/{session_id}/host/quiz-request"),
            ("DELETE", "/api/{session_id}/host/quiz-preview"),
            ("POST",   "/api/{session_id}/host/quiz-refine"),
            ("POST",   "/api/{session_id}/host/misc/paste-dismiss"),
            ("GET",    "/api/{session_id}/host/misc/feedback"),
        ]
        missing = [
            f"{m} {p}" for m, p in required
            if not _find_app_match(m, p, app_routes)
        ]
        assert not missing, "Core host routes missing:\n" + "\n".join(missing)


# ── Test: global spec endpoints ────────────────────────────────────────────────

class TestGlobalApiContract:
    """Endpoints in x-global-paths (no session_id) must also exist on the app."""

    def test_transcription_language_endpoints_exist(self, app_routes):
        required = [
            ("POST", "/api/transcription-language"),
            ("GET",  "/api/transcription-language/request"),
        ]
        missing = [
            f"{m} {p}" for m, p in required
            if not _find_app_match(m, p, app_routes)
        ]
        assert not missing, "Global endpoints missing:\n" + "\n".join(missing)


# ── Test: undocumented routes (informational) ──────────────────────────────────

class TestUndocumentedRoutes:
    """Report routes on the daemon that are not in any spec.

    This test does NOT fail on undocumented routes — it only reports them
    as warnings so developers are aware of undocumented surface area.
    """

    def test_report_undocumented_routes(self, app_routes, capsys):
        participant_spec = _load_spec(PARTICIPANT_SPEC_PATH)
        host_spec = _load_spec(HOST_SPEC_PATH)

        # Build all spec paths (with full prefixes)
        spec_full_paths: set[tuple[str, str]] = set()

        for method, path in _spec_paths_to_route_set(participant_spec):
            spec_full_paths.add((method, "/api/participant" + path))

        for method, path in _spec_paths_to_route_set(host_spec):
            spec_full_paths.add((method, "/api/{session_id}" + path))

        # Global paths from x-global-paths section (not standard OpenAPI, handled manually)
        spec_full_paths.add(("POST", "/api/transcription-language"))
        spec_full_paths.add(("GET",  "/api/transcription-language/request"))

        undocumented = []
        for method, path in sorted(app_routes):
            # Skip FastAPI internal + catch-all proxy + static
            if path in _FASTAPI_INTERNAL_PREFIXES:
                continue
            # Catch-all proxy: /api/{path:path} rendered as /api/{path} in openapi
            if re.search(r"\{path[^}]*\}", path):
                continue
            if any(path.startswith(p.rstrip("/")) for p in _KNOWN_UNSPECCED_PREFIXES):
                continue
            # Check if this app path matches any spec path
            matched = any(
                spec_method == method and _paths_match(spec_path, path)
                for spec_method, spec_path in spec_full_paths
            )
            if not matched:
                undocumented.append(f"  {method} {path}")

        if undocumented:
            print(
                "\n[INFO] Daemon routes NOT in any spec (not a failure):\n"
                + "\n".join(undocumented)
            )
