/** @type {import('tailwindcss').Config} */
module.exports = {
    content: ["./static/**/*.html", "./static/**/*.js"],
    darkMode: "class",
    plugins: [
        require('@tailwindcss/forms'),
        require('@tailwindcss/container-queries'),
        require('@tailwindcss/typography'),
    ],
    theme: {
        extend: {
            "colors": {
                "on-primary-container": "#3747ac",
                "on-primary-fixed-variant": "#4252b7",
                "surface-variant": "#d9e4ea",
                "surface": "#f7f9fb",
                "primary-container": "#dfe0ff",
                "secondary-container": "#d5e3fc",
                "on-surface-variant": "#566166",
                "primary-fixed": "#dfe0ff",
                "on-tertiary-fixed-variant": "#4d5870",
                "surface-container": "#e8eff3",
                "error-dim": "#4f0116",
                "outline-variant": "#a9b4b9",
                "secondary-fixed-dim": "#c7d5ed",
                "primary": "#4555ba",
                "primary-fixed-dim": "#cdd1ff",
                "secondary-fixed": "#d5e3fc",
                "secondary-dim": "#465468",
                "tertiary-dim": "#48536b",
                "surface-tint": "#4555ba",
                "outline": "#717c82",
                "primary-dim": "#3848ad",
                "surface-container-highest": "#d9e4ea",
                "surface-container-lowest": "#ffffff",
                "on-primary-fixed": "#223399",
                "on-secondary-fixed": "#324053",
                "tertiary-fixed-dim": "#c3cfeb",
                "on-tertiary-container": "#434e66",
                "inverse-surface": "#0b0f10",
                "on-tertiary-fixed": "#303c53",
                "on-error-container": "#782232",
                "on-secondary-fixed-variant": "#4e5c71",
                "error": "#9e3f4e",
                "on-surface": "#2a3439",
                "inverse-primary": "#7e8ef7",
                "on-tertiary": "#f9f8ff",
                "surface-dim": "#cfdce3",
                "on-error": "#fff7f7",
                "surface-bright": "#f7f9fb",
                "background": "#f7f9fb",
                "on-primary": "#f9f6ff",
                "tertiary": "#545f78",
                "on-secondary-container": "#455367",
                "error-container": "#ff8b9a",
                "surface-container-high": "#e1e9ee",
                "on-background": "#2a3439",
                "secondary": "#526074",
                "surface-container-low": "#f0f4f7",
                "inverse-on-surface": "#9a9d9f",
                "tertiary-fixed": "#d1ddfa",
                "tertiary-container": "#d1ddfa",
                "on-secondary": "#f8f8ff"
            },
            "borderRadius": {
                "DEFAULT": "0.125rem",
                "lg": "0.25rem",
                "xl": "0.5rem",
                "full": "0.75rem"
            },
            "fontFamily": {
                "headline": ["Manrope"],
                "body": ["Manrope"],
                "label": ["Manrope"]
            }
        },
    },
}
