@startuml
hide footbox

participant "Host"
participant "Participant"
participant "Railway"
participant "Daemon"

"Daemon" --> "Participant": broadcast notes_updated
"Daemon" --> "Participant": broadcast summary_updated
"Host" -> "Daemon": DELETE /api/{session_id}/host/scores
"Daemon" --> "Participant": broadcast scores_updated
"Host" -> "Daemon": GET /host/{session_id}
"Host" -> "Daemon": GET /api/{session_id}/host/state
"Participant" -> "Daemon": POST /api/participant/register
"Railway" -> "Daemon": GET /{session_id}/api/slides
"Daemon" --> "Host": notify_host participant_list_updated
"Participant" -> "Daemon": GET /api/participant/state
"Participant" -> "Daemon": POST /api/participant/location
"Daemon" --> "Participant": broadcast active_participants_count_updated
"Participant" -> "Daemon": PUT /api/participant/name
"Host" -> "Daemon": PUT /api/{session_id}/host/activity
"Daemon" --> "Participant": broadcast activity_updated
"Participant" -> "Daemon": POST /api/participant/qa/submit
"Daemon" --> "Host": notify_host qa_updated
"Daemon" --> "Host": notify_host scores_updated
"Participant" -> "Daemon": POST /api/participant/qa/upvote
"Host" -> "Daemon": PUT /api/{session_id}/host/qa/question/{question_id}/answered
"Daemon" --> "Participant": broadcast qa_updated

@enduml
