@startuml
hide footbox
title Feature: Live Poll
caption <color:gray>Generated 2026-04-27 16:06</color>

participant "Host"
participant "Participant\nAlice"
participant "Daemon"
participant "Railway"

== Participant can vote in next poll after previous closed by timer ==
group #F5F5F5 init
  "Host" -> "Daemon": DELETE /api/{session_id}/host/scores <color:#1F77B4>[1]</color>
  "Host" -> "Daemon": GET /host/{session_id} <color:#D62728>[2]</color>
  "Host" -> "Daemon": GET /api/{session_id}/host/state <color:#2CA02C>[3]</color>
  "Host" -> "Daemon": GET /api/{session_id}/host/poll <color:#FF7F0E>[4]</color>
  "Host" -> "Daemon": PUT /api/{session_id}/host/activity <color:#9467BD>[5]</color>
  activate "Daemon"
  "Daemon" --> "Participant\nAlice": activity_updated <color:#9467BD>[5]</color>
  deactivate "Daemon"
  "Host" -> "Daemon": POST /api/{session_id}/host/poll/manual/submit <color:#17BECF>[6]</color>
  activate "Daemon"
  "Daemon" --> "Participant\nAlice": poll_opened <color:#17BECF>[6]</color>
  "Daemon" --> "Host": poll_opened <color:#17BECF>[6]</color>
  deactivate "Daemon"
  "Participant\nAlice" -> "Railway": GET /{session_id}/ <color:#BCBD22>[7]</color>
  "Participant\nAlice" -> "Daemon": POST /api/participant/register <color:#E377C2>[8]</color>
  activate "Daemon"
  "Daemon" --> "Host": participant_list_updated <color:#E377C2>[8]</color>
  deactivate "Daemon"
  "Participant\nAlice" -> "Daemon": GET /api/participant/state <color:#8C564B>[9]</color>
  "Participant\nAlice" -> "Daemon": GET /{session_id}/api/slides <color:#7F7F7F>[10]</color>
  "Daemon" --> "Participant\nAlice": active_participants_count_updated <color:#1F77B4>[11]</color>
end
"Host" -> "Daemon": POST /api/{session_id}/host/poll/end/timer <color:#D62728>[12]</color>
activate "Daemon"
"Daemon" --> "Participant\nAlice": poll_end_countdown_started <color:#D62728>[12]</color>
"Daemon" --> "Host": poll_end_countdown_started <color:#D62728>[12]</color>
deactivate "Daemon"
"Participant\nAlice" -> "Daemon": PUT /api/participant/name <color:#2CA02C>[13]</color>
activate "Daemon"
"Daemon" --> "Host": participant_list_updated <color:#2CA02C>[13]</color>
deactivate "Daemon"
"Host" -> "Daemon": POST /api/{session_id}/host/poll/end <color:#FF7F0E>[14]</color>
activate "Daemon"
"Daemon" --> "Participant\nAlice": poll_ended <color:#FF7F0E>[14]</color>
"Daemon" --> "Host": poll_ended <color:#FF7F0E>[14]</color>
deactivate "Daemon"
"Host" -> "Daemon": GET /api/{session_id}/host/poll <color:#9467BD>[15]</color>
"Host" -> "Daemon": GET /api/{session_id}/host/poll <color:#17BECF>[16]</color>
"Host" -> "Daemon": GET /api/{session_id}/host/poll <color:#BCBD22>[17]</color>
"Host" -> "Daemon": POST /api/{session_id}/host/poll/manual/submit <color:#E377C2>[18]</color>
activate "Daemon"
"Daemon" --> "Participant\nAlice": poll_opened <color:#E377C2>[18]</color>
"Daemon" --> "Host": poll_opened <color:#E377C2>[18]</color>
deactivate "Daemon"
"Participant\nAlice" -> "Daemon": POST /api/participant/poll/vote <color:#8C564B>[19]</color>
activate "Daemon"
"Daemon" --> "Host": vote_update <color:#8C564B>[19]</color>
deactivate "Daemon"
"Host" -> "Daemon": GET /api/{session_id}/host/poll <color:#7F7F7F>[20]</color>


@enduml
